---
- name: Configure all servers
  hosts: all
  become: true
  roles:
    - common

- name: Configure database server
  hosts: db
  become: true
  roles:
    - mysql

- name: Configure web server
  hosts: web
  become: true
  roles:
    - firewall
    - nginx
    - app
    - docker
