---
- name: Install MariaDB Server
  apt:
    name:
      - mariadb-server
      - python3-pymysql
    state: present
    update_cache: yes

- name: Start and enable MariaDB
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Create database
  community.mysql.mysql_db:
    name: homedb
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Create database user
  community.mysql.mysql_user:
    name: arun
    password: Arun@12345
    priv: "homedb.*:ALL"
    host: "%"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock
