---
galaxy_info:
  author: Arun P S
  description: Deploy a multi-tier web application using Ansible
  company: Personal Project
  license: MIT
  min_ansible_version: "2.16"

  galaxy_tags:
    - ansible
    - nginx
    - mariadb
    - docker

dependencies: []
