---
- name: Clone GitHub Repository
  ansible.builtin.git:
    repo: "https://github.com/Arunps1105/multi-tier-webapp.git"
    dest: /var/www/html/multi-tier-webapp
    version: main
    force: true

- name: Copy Website Files
  ansible.builtin.copy:
    src: /var/www/html/multi-tier-webapp/
    dest: /usr/share/nginx/html/
    remote_src: true
    owner: root
    group: root
    mode: "0755"

- name: Restart Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
