---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Upgrade all packages
  apt:
    upgrade: dist

- name: Install required packages
  apt:
    name:
      - git
      - curl
      - vim
      - unzip
    state: present
