name: Deploy with Ansible

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible python3-pip
          pip3 install ansible-lint

      - name: Playbook Syntax Check
        run: ansible-playbook --syntax-check site.yml

      - name: Ansible Lint
        run: ansible-lint

      - name: Playbook Syntax Check
        run: ansible-playbook --syntax-check site.yml
